### ISSUE TITLE
TreeHash fails on chunks > 3MB

### ISSUE THREAD

**Issue by purohit** [rdwilliamson/aws#13]
Hello,

I've been doing some extensive debugging and believe I've found an issue with the treehasher: it doesn't pass tests for parts greater than 3MB. If I construct a data array in advance of, say, 3.5 MB of the byte 'a', and write it all at once to the TreeHasher, the checksum it calculates is wrong.

If instead I write the byte 'a' to the treehasher iteratively (3.5 MB worth), it outputs the correct checksum. For cases (1 << 20), (2 << 20), (3 << 20), both ways output the same result, and are correct. Do you know what might be the problem? I've hand-computed the checksums and also checked them against other repos (for example, https://github.com/jclouds/jclouds-labs-aws/blob/master/glacier/src/test/java/org/jclouds/glacier/util/TreeHashTest.java#L68 for the canonical treehash of the 3.5 MB bytestring; https://chromium.googlesource.com/external/boto/+/master/tests/unit/glacier/test_utils.py#108 for 4MB), so I don't think the checksum in the test case itself is the problem.

I've uploaded the failing test cases. 3.5 and 4 fail. Note that everything smaller, passes. https://github.com/recursionpharma/aws/blob/treehasher/glacier/treehash_test.go#L93

Please let me know.

Thanks!

**Comment by rdwilliamson** [comment]
Thanks for the report. The basic process of writing to the TreeHash is if the data doesn't fill whats remaining of a 1mb chunk just copy the data into the chunk (writing a byte at a time is going to hit this case most of the time). Otherwise the write can fill the 1mb chunk so it does, the chunk is then hashed and added (the Add from #11). Then all full 1mb parts of the input data are hashed and added. Finally the remaining data is copy into the 1mb chunk (similar to the first case). So writing 3.5mb a byte at a time and writing 3.5mb at once take separate code paths. I would suspect the bug lies there.

I'll be looking into this and #11 this weekend.

**Comment by purohit** [comment]
Understood, thanks for the explanation. I refactored and fixed the code so TreeHash passes all test cases, and that both MultiTreeHash and TreeHash use the same code. The commit is in with #11. Now on my side multipart glacier uploads with larger chunk sizes work fine.

**Comment by rdwilliamson** [comment]
Thanks for fixing this. I'm leaving the issue open because I'd like to take a look at reducing memory usage. Below is the difference of before and after merging #12 (I'm aware it's not really fair to compare broken to working code). I'm also not sure how the original implementation has 0 bytes, it's building up a list of nodes and they have to go somewhere.

```
benchmark             old ns/op     new ns/op     delta
BenchmarkTreeHash     11530         12264         +6.37%

benchmark             old MB/s     new MB/s     speedup
BenchmarkTreeHash     88.81        83.49        0.94x

benchmark             old allocs     new allocs     delta
BenchmarkTreeHash     0              0              +0.00%

benchmark             old bytes     new bytes     delta
BenchmarkTreeHash     0             5019          +Inf%
```

**Comment by purohit** [comment]
Yeah, that's a bit weird about the 0 ops. Right now I'm re-constructing a list for every level in the tree where newly-promoted nodes go, but it could certainly be done in-place with one leaf-node list with a little more care about indices. That would probably alleviate some of the performance issues.

**Comment by rdwilliamson** [comment]
I've converted the Write method to avoid allocation or copying too much in 996ef14ad5c8ce7705ab40d5a65bbf2c31e3cd55 and treeHash to build the root node in place in ef1a74249f6049bb04419ad63d1aec133e75e4ba.
